<a href="https://colab.research.google.com/github/jdcj222/DLProject/blob/master/week1/4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])

In [5]:
m[1,2]

7

In [6]:
m[2,4]

14

In [8]:
m[1,1:3]

array([6, 7])

In [9]:
m[1:3,2]

array([ 7, 12])

In [12]:
m[0:2,3:5]

array([[3, 4],
       [8, 9]])