<a href="https://colab.research.google.com/github/jdcj222/DLProject/blob/master/week1/4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [5]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [14]:
x[(x%3==0)&(x%4==1)]

array([9])